// <auto-generated />
using Contactista.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contactista.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Contactista.Domain.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "Alexandria",
                            FullName = "Mahmoud Samy",
                            PhoneNumber = "01024236263"
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "Cairo",
                            FullName = "Ahmed Ali",
                            PhoneNumber = "01100000000"
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "Cairo",
                            FullName = "Hazem Ahmed",
                            PhoneNumber = "01200000000"
                        },
                        new
                        {
                            ContactId = 4,
                            Address = "Cairo",
                            FullName = "Omar Marzok",
                            PhoneNumber = "01500000000"
                        },
                        new
                        {
                            ContactId = 5,
                            Address = "Cairo",
                            FullName = "Reda Tantawey",
                            PhoneNumber = "01000000000"
                        });
                });

            modelBuilder.Entity("Contactista.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "??, ????9?0?!?+???]?+}????????.*	?9?$&7??3??;xC/E????(\r/",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Password = ")wY??????b5????????v.ZWU.??T?_??\"e,9??????~	?????!?%?	?",
                            Username = "user2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
